INSERT INTO gifts (name, status) VALUES
('Jogo de Cama 1', 'Disponível'),
('Jogo de Cama 2', 'Disponível'),
('Jogo de Cama 3', 'Disponível'),
('Jogo de Toalhas 1', 'Disponível'),
('Jogo de Toalhas 2', 'Disponível'),
('Mesinha Bar/Café', 'Disponível'),
('Jogo de Copos', 'Disponível'),
('Aparelho de Jantar', 'Disponível'),
('Jogo de Bowl para Sopa/Sobremesa', 'Disponível'),
('Fechadura Eletrônica', 'Disponível'),
('Kit Lavabo', 'Disponível'),
('Kit Banheiro Casal', 'Disponível'),
('Fruteira de Mesa', 'Disponível'),
('Kit Organizadores Para Ele', 'Disponível'),
('Kit Organizadores Para Ela', 'Disponível'),
('Aspirador de Pó', 'Disponível'),
('Capacho', 'Disponível'),
('2 Tapetes para Banheiro Antiderrapante', 'Disponível'),
('Frigideira com Alça Removível', 'Disponível'),
('Forma de Pão', 'Disponível'),
('Coberdrom Dupla Face', 'Disponível'),
('Escultura de Parede - Tam G', 'Disponível'),
('Capas para Almofadas', 'Disponível'),
('Lixeira + Limpador Lavabo', 'Disponível'),
('Cadeira de Escritório', 'Disponível');

